### ISSUE TITLE
2 nieuwe algoritmen

### ISSUE THREAD

**Issue by SandervWickeren** [SandervWickeren/Heuristics_Amstelhaege#9]
Het eerste algoritmen kunnen we aankaarten als het "random algoritme" waarmee we uitgaan dat we met "geluk" een goede oplossing vinden. Naast deze moeten we nog twee algoritmes vinden.

Misschien vanaf links onder beginnen en grootste eerst (zoals in die presentatie)? Of zijn er andere dingen in de literatuur te vinden?

Misschien zelf een goed patroon bedenken en deze laten voeden in een bepaald algoritmen?

**Comment by LauraGeerars** [comment]
Hill Climbers algoritme

**Comment by LauraGeerars** [comment]
Simulated enhealing algoritme
